import type { CustomerProjectFilter } from '@/lib/customerProjectProjection';

export type SalesCustomerLocale = 'ko' | 'vi' | 'en';

export const salesCustomerCopy = {
  ko: {
    title: '고객·담당자·프로젝트 이력',
    description: '고객과 담당자를 기준으로 접수 완료된 프로젝트 이력을 통합 관리합니다.',
    dashboard: '영업 대시보드', customers: '고객·주소록', search: '고객·담당자·프로젝트번호·PM·부서 검색',
    addCustomer: '고객 등록', addContact: '담당자 등록', businessCard: '명함 자동등록', import: '연락처 불러오기', export: '연락처 내보내기',
    total: '전체 고객', active: '진행 프로젝트', newYear: '올해 신규', completed: '최근 완료', linkReview: '연결 검토', cardReview: '명함 검토', stale: '장기 미접촉',
    quick: '업무 바로가기', recent: '최근 프로젝트 연결', activeCustomers: '진행 고객사', activeCustomersHelp: '현재 진행 중인 프로젝트가 있는 고객사입니다.', directory: '고객 디렉터리', selected: '선택됨', noCustomers: '조건에 맞는 고객이 없습니다.', activeShort: '진행', completedShort: '완료',
    basic: '기본정보', contacts: '담당자', projects: '프로젝트 이력', cards: '명함 이력', audit: '관계 감사',
    customerNo: '고객번호', industry: '업종', owner: '담당자', status: '상태', note: '메모', lastActivity: '최근 활동', currentContact: '현재 담당자', intakeDate: '접수일', contactProjectFilter: '담당 프로젝트만 표시', clearFilter: '전체 담당자',
    projectNo: '프로젝트번호', projectName: '프로젝트명', pm: 'PM', unit: '담당부서', projectStatus: '진행상태', contactSnapshot: '접수 당시 담당자', openProject: '프로젝트 열기',
    readOnlyLegacy: '기존 영업기회·활동은 이관 검토를 위한 읽기 전용 자료입니다.', noProjects: '접수 완료된 프로젝트 이력이 없습니다.', noContacts: '등록된 담당자가 없습니다.',
    noCards: '연결된 명함 이력이 없습니다.', noAudit: '관계 변경 이력이 없습니다.', estimate: '견적 의뢰관리 열기', mail: '메일 작성', timeline: '고객 활동 타임라인', cardInbox: '명함 수신함', projectIntake: '프로젝트 접수 열기',
    demo: 'DEMO_LOCAL 데이터입니다. 서버 연결 전에는 운영 고객정보로 저장되지 않습니다.', backend: '운영 저장은 Backend Adapter 연결 후 가능합니다.',
    legacyPipeline: '영업기회 Pipeline은 종료되었습니다. 고객·프로젝트 이력에서 확인하거나 견적 의뢰를 시작하세요.',
    legacyQuotes: '견적서는 프로젝트 영역의 견적서 관리에서 계속 관리합니다.', legacyContracts: '계약·수주는 견적 의뢰의 수주 판정과 canonical Project를 사용합니다.',
    legacyActivities: '영업활동은 고객별 타임라인에서 읽기 전용으로 확인합니다.', goCanonical: '공식 업무 화면으로 이동',
    save: '저장', cancel: '취소', name: '이름', customer: '고객사', department: '부서', position: '직위', email: '이메일', phone: '전화', detail: '담당자 상세', cardHistory: '명함 이력', imported: '검토한 연락처를 반영했습니다.', representative: '대표 연락처', address: '주소', homepage: '홈페이지', source: '등록 Source', updatedAt: '최근 업데이트', period: '수행 기간', startTbd: '착수일 미정', projectFilters: { ALL: '전체', PRE_WORK: '착수 전', ACTIVE: '진행 중', COMPLETED: '납품·완료', REVISION: '수정', CLOSED: '종결' },
  },
  vi: {
    title: 'Khách hàng, liên hệ và lịch sử dự án',
    description: 'Quản lý khách hàng, người liên hệ và lịch sử dự án đã tiếp nhận trong một nơi.',
    dashboard: 'Bảng điều khiển kinh doanh', customers: 'Khách hàng & danh bạ', search: 'Tìm khách hàng, liên hệ, mã dự án, PM hoặc bộ phận',
    addCustomer: 'Thêm khách hàng', addContact: 'Thêm liên hệ', businessCard: 'Đăng ký danh thiếp', import: 'Nhập liên hệ', export: 'Xuất liên hệ',
    total: 'Tổng khách hàng', active: 'Dự án đang chạy', newYear: 'Mới trong năm', completed: 'Mới hoàn thành', linkReview: 'Cần kiểm tra liên kết', cardReview: 'Cần kiểm tra danh thiếp', stale: 'Lâu chưa liên hệ',
    quick: 'Truy cập nhanh', recent: 'Liên kết dự án gần đây', activeCustomers: 'Khách hàng có dự án đang chạy', activeCustomersHelp: 'Khách hàng có dự án hiện đang được thực hiện.', directory: 'Danh bạ khách hàng', selected: 'Đã chọn', noCustomers: 'Không có khách hàng phù hợp.', activeShort: 'Đang chạy', completedShort: 'Hoàn tất',
    basic: 'Thông tin cơ bản', contacts: 'Người liên hệ', projects: 'Lịch sử dự án', cards: 'Lịch sử danh thiếp', audit: 'Kiểm toán quan hệ',
    customerNo: 'Mã khách hàng', industry: 'Ngành', owner: 'Phụ trách', status: 'Trạng thái', note: 'Ghi chú', lastActivity: 'Hoạt động gần nhất', currentContact: 'Liên hệ hiện tại', intakeDate: 'Ngày tiếp nhận', contactProjectFilter: 'Chỉ hiển thị dự án của liên hệ', clearFilter: 'Tất cả liên hệ',
    projectNo: 'Mã dự án', projectName: 'Tên dự án', pm: 'PM', unit: 'Bộ phận', projectStatus: 'Trạng thái', contactSnapshot: 'Liên hệ khi tiếp nhận', openProject: 'Mở dự án',
    readOnlyLegacy: 'Cơ hội và hoạt động cũ chỉ được đọc để phục vụ kiểm tra chuyển đổi.', noProjects: 'Chưa có lịch sử dự án đã tiếp nhận.', noContacts: 'Chưa có người liên hệ.',
    noCards: 'Chưa có lịch sử danh thiếp liên kết.', noAudit: 'Chưa có lịch sử thay đổi quan hệ.', estimate: 'Mở quản lý yêu cầu báo giá', mail: 'Soạn email', timeline: 'Dòng thời gian khách hàng', cardInbox: 'Hộp thư danh thiếp', projectIntake: 'Mở tiếp nhận dự án',
    demo: 'Đây là dữ liệu DEMO_LOCAL và không được lưu thành dữ liệu vận hành trước khi kết nối máy chủ.', backend: 'Chỉ có thể lưu vận hành sau khi kết nối Backend Adapter.',
    legacyPipeline: 'Pipeline cơ hội đã kết thúc. Hãy dùng lịch sử khách hàng·dự án hoặc tạo yêu cầu báo giá.',
    legacyQuotes: 'Báo giá tiếp tục được quản lý tại màn hình báo giá của khu vực dự án.', legacyContracts: 'Hợp đồng và trúng thầu dùng quyết định thương mại và canonical Project.',
    legacyActivities: 'Hoạt động kinh doanh cũ chỉ được đọc trong dòng thời gian khách hàng.', goCanonical: 'Đi đến màn hình chính thức',
    save: 'Lưu', cancel: 'Hủy', name: 'Tên', customer: 'Khách hàng', department: 'Bộ phận', position: 'Chức vụ', email: 'Email', phone: 'Điện thoại', detail: 'Chi tiết liên hệ', cardHistory: 'Lịch sử danh thiếp', imported: 'Đã áp dụng các liên hệ được duyệt.', representative: 'Liên hệ chính', address: 'Địa chỉ', homepage: 'Trang web', source: 'Nguồn đăng ký', updatedAt: 'Cập nhật gần nhất', period: 'Thời gian thực hiện', startTbd: 'Chưa xác định ngày bắt đầu', projectFilters: { ALL: 'Tất cả', PRE_WORK: 'Trước khởi công', ACTIVE: 'Đang thực hiện', COMPLETED: 'Đã giao·hoàn tất', REVISION: 'Chỉnh sửa', CLOSED: 'Đã đóng' },
  },
  en: {
    title: 'Customer, contact, and project history',
    description: 'Manage customers, contacts, and accepted project history in one operational view.',
    dashboard: 'Sales dashboard', customers: 'Customers & contacts', search: 'Search customer, contact, project number, PM, or unit',
    addCustomer: 'Add customer', addContact: 'Add contact', businessCard: 'Business card registration', import: 'Import contacts', export: 'Export contacts',
    total: 'Customers', active: 'Active projects', newYear: 'New this year', completed: 'Recently completed', linkReview: 'Link review', cardReview: 'Card review', stale: 'Stale customers',
    quick: 'Quick actions', recent: 'Recent project links', activeCustomers: 'Active customers', activeCustomersHelp: 'Customers with projects currently in progress.', directory: 'Customer directory', selected: 'Selected', noCustomers: 'No customers match the filters.', activeShort: 'Active', completedShort: 'Done',
    basic: 'Basic', contacts: 'Contacts', projects: 'Project history', cards: 'Business card history', audit: 'Relationship audit',
    customerNo: 'Customer number', industry: 'Industry', owner: 'Owner', status: 'Status', note: 'Note', lastActivity: 'Last activity', currentContact: 'Current contact', intakeDate: 'Intake date', contactProjectFilter: 'Showing this contact\'s projects', clearFilter: 'All contacts',
    projectNo: 'Project number', projectName: 'Project name', pm: 'PM', unit: 'Unit', projectStatus: 'Status', contactSnapshot: 'Contact at intake', openProject: 'Open project',
    readOnlyLegacy: 'Legacy opportunities and activities remain read-only migration evidence.', noProjects: 'No accepted project history is available.', noContacts: 'No contacts are registered.',
    noCards: 'No linked business card history is available.', noAudit: 'No relationship audit history is available.', estimate: 'Open estimate requests', mail: 'Compose mail', timeline: 'Customer activity timeline', cardInbox: 'Business card inbox', projectIntake: 'Open project intake',
    demo: 'This is DEMO_LOCAL data and is not saved as operational customer data before server integration.', backend: 'Operational saves require the Backend Adapter.',
    legacyPipeline: 'The opportunity pipeline has retired. Use customer project history or start an estimate request.',
    legacyQuotes: 'Estimate sheets continue in the canonical project estimate workspace.', legacyContracts: 'Contracts and awards use the commercial decision and canonical Project.',
    legacyActivities: 'Legacy sales activities are read-only in each customer timeline.', goCanonical: 'Open canonical workspace',
    save: 'Save', cancel: 'Cancel', name: 'Name', customer: 'Customer', department: 'Department', position: 'Position', email: 'Email', phone: 'Phone', detail: 'Contact details', cardHistory: 'Card history', imported: 'Reviewed contacts were applied.', representative: 'Primary contact', address: 'Address', homepage: 'Website', source: 'Registration source', updatedAt: 'Last updated', period: 'Project period', startTbd: 'Start date TBD', projectFilters: { ALL: 'All', PRE_WORK: 'Pre-work', ACTIVE: 'Active', COMPLETED: 'Delivered·completed', REVISION: 'Revision', CLOSED: 'Closed' },
  },
} as const;

export const filterLabels = (locale: SalesCustomerLocale): Record<CustomerProjectFilter, string> => ({
  ALL: salesCustomerCopy[locale].total,
  ACTIVE_PROJECTS: salesCustomerCopy[locale].active,
  NEW_THIS_YEAR: salesCustomerCopy[locale].newYear,
  RECENTLY_COMPLETED: salesCustomerCopy[locale].completed,
  LINK_REVIEW: salesCustomerCopy[locale].linkReview,
  BUSINESS_CARD_REVIEW: salesCustomerCopy[locale].cardReview,
  STALE_CUSTOMERS: salesCustomerCopy[locale].stale,
});
